name: SPOT weekly when2meet posts

# Controls when the workflow will run
on:
  schedule:
    - cron: "45 11 * * 4"  # 11:45am UTC Thursday (4 = Thursday). Github says that most demand is at top of the hour, so I avoid
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: spot-weekly-posts

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Uses python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      
      # Runs a single command using the runners shell
      - run: pip install -r requirements.txt
      - run: python scripts/slack.py
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_APP_ID: ${{ secrets.SLACK_APP_ID }}
  